"""Add users table and user_id to profiles

Revision ID: e728af7d89a1
Revises:
Create Date: 2026-05-13 14:36:53.186852

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision = 'e728af7d89a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Create users table first
    op.create_table('users',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # Step 2: Add user_id as nullable first (to handle existing data)
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_business_profiles_user_id'), ['user_id'], unique=False)

    # Step 3: Create a default user for legacy data
    default_user_id = '00000000-0000-0000-0000-000000000000'
    op.execute(f"INSERT INTO users (id, email, password_hash, name, created_at, updated_at) VALUES ('{default_user_id}', 'legacy@system.local', 'legacy', 'Legacy Data', NOW(), NOW())")

    # Step 4: Set existing profiles to use the default user
    op.execute("UPDATE business_profiles SET user_id = '00000000-0000-0000-0000-000000000000' WHERE user_id IS NULL")

    # Step 5: Now make it NOT NULL
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_business_profiles_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###